download_links = {
    "chrome": "https://www.google.com/chrome/",
    "firefox": "https://www.mozilla.org/firefox/new/",
    "notepad++": "https://notepad-plus-plus.org/downloads/",
    "visual studio code": "https://code.visualstudio.com/Download",
    "spotify": "https://www.spotify.com/download/",
    "discord": "https://discord.com/download",
    "vlc": "https://www.videolan.org/vlc/",
    "7-zip": "https://www.7-zip.org/download.html",
    "winrar": "https://www.win-rar.com/download.html",
    "skype": "https://www.skype.com/en/get-skype/",
    "zoom": "https://zoom.us/download",
    "slack": "https://slack.com/downloads/",
    "git": "https://git-scm.com/downloads",
    "docker": "https://www.docker.com/get-started",
    "python": "https://www.python.org/downloads/",
    "java": "https://www.java.com/en/download/",
    "node.js": "https://nodejs.org/en/download/",
    "eclipse": "https://www.eclipse.org/downloads/",
    "intellij idea": "https://www.jetbrains.com/idea/download/",
    "microsoft teams": "https://www.microsoft.com/en-us/microsoft-teams/download-app",
    "dropbox": "https://www.dropbox.com/install",
    "onedrive": "https://www.microsoft.com/en-us/microsoft-365/onedrive/download",
    "adobe reader": "https://get.adobe.com/reader/",
    "gimp": "https://www.gimp.org/downloads/",
    "inkscape": "https://inkscape.org/release/",
    "blender": "https://www.blender.org/download/",
    "audacity": "https://www.audacityteam.org/download/",
    "obs studio": "https://obsproject.com/download",
    "steam": "https://store.steampowered.com/about/",
    "epic games": "https://store.epicgames.com/en-US/download",
    "origin": "https://www.origin.com/download",
    "battle.net": "https://www.blizzard.com/en-us/apps/battle.net/desktop",
    "uplay": "https://ubisoftconnect.com/",
    "twitch": "https://app.twitch.tv/download",
    "adobe photoshop": "https://www.adobe.com/products/photoshop/free-trial-download.html",
    "adobe premiere pro": "https://www.adobe.com/products/premiere/free-trial-download.html",
    "kodi": "https://kodi.tv/download",
    "handbrake": "https://handbrake.fr/downloads.php",
    "winamp": "https://www.winamp.com/",
    "cisco webex": "https://www.webex.com/downloads.html",
    "microsoft office": "https://www.microsoft.com/en-us/microsoft-365/get-started-with-office-2019",
    "libreoffice": "https://www.libreoffice.org/download/download/",
    "openoffice": "https://www.openoffice.org/download/",
    "virtualbox": "https://www.virtualbox.org/wiki/Downloads",
    "vmware": "https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html",
    "kaspersky": "https://usa.kaspersky.com/downloads",
    "avast": "https://www.avast.com/en-us/free-antivirus-download",
    "malwarebytes": "https://www.malwarebytes.com/mwb-download",
    "ccleaner": "https://www.ccleaner.com/ccleaner/download",
    "r studio": "https://rstudio.com/products/rstudio/download/",
    "maven": "https://maven.apache.org/download.cgi",
    "apache tomcat": "https://tomcat.apache.org/download-90.cgi",
    "android studio": "https://developer.android.com/studio",
    "postman": "https://www.postman.com/downloads/",
    "teamviewer": "https://www.teamviewer.com/en/download/",
    "anydesk": "https://anydesk.com/en/downloads",
    "tor browser": "https://www.torproject.org/download/",
    "opera": "https://www.opera.com/download",
    "cyberduck": "https://cyberduck.io/download/",
    "filezilla": "https://filezilla-project.org/download.php",
    "lightshot": "https://app.prntscr.com/en/download.html",
    "gyazo": "https://gyazo.com/download",
    "bluejeans": "https://www.bluejeans.com/downloads",
    "zoomtext": "https://www.zoomtext.com/downloads/",
    "kmplayer": "https://www.kmplayer.com/download",
    "potplayer": "https://potplayer.daum.net/",
    "guitar pro": "https://www.guitar-pro.com/en/index.php?pg=download",
    "reaper": "https://www.reaper.fm/download.php",
    "ableton live": "https://www.ableton.com/en/trial/",
    "cubase": "https://new.steinberg.net/cubase/trial/",
    "bitdefender": "https://www.bitdefender.com/solutions/free.html",
    "trend micro": "https://www.trendmicro.com/en_us/forHome/products/free-tools.html",
    "avg antivirus": "https://www.avg.com/en-us/free-antivirus-download",
    "eset": "https://www.eset.com/us/home/for-windows/",
    "panda antivirus": "https://www.pandasecurity.com/en/homeusers/download/",
    "comodo": "https://www.comodo.com/home/internet-security/free-internet-security.php",
    "wampserver": "https://www.wampserver.com/en/",
    "xampp": "https://www.apachefriends.org/download.html",
    "putty": "https://www.putty.org/",
    "winscp": "https://winscp.net/eng/download.php",
    "cygwin": "https://cygwin.com/install.html",
    "raspberry pi imager": "https://www.raspberrypi.org/software/",
    "arduino": "https://www.arduino.cc/en/software",
    "tortoisesvn": "https://tortoisesvn.net/downloads.html",
    "gitkraken": "https://www.gitkraken.com/download",
    "jira": "https://www.atlassian.com/software/jira/download",
    "confluence": "https://www.atlassian.com/software/confluence/download",
    # Add more software as needed
}